//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quartz.Server.QYService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", ConfigurationName="QYService.IndicatorGisWSInterface")]
    public interface IndicatorGisWSInterface {
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Quartz.Server.QYService.queryReportIndicatorResponse queryReportIndicator(Quartz.Server.QYService.queryReportIndicator request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Quartz.Server.QYService.queryTypeResponse queryType(Quartz.Server.QYService.queryType request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Quartz.Server.QYService.queryAreaVOResponse queryAreaVO(Quartz.Server.QYService.queryAreaVO request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Quartz.Server.QYService.transferDataResponse transferData(Quartz.Server.QYService.transferData request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Quartz.Server.QYService.queryUnitsAreaResponse queryUnitsArea(Quartz.Server.QYService.queryUnitsArea request);
        
        // CODEGEN: 参数“arg0”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Quartz.Server.QYService.updateBiIndicatorResponse updateBiIndicator(Quartz.Server.QYService.updateBiIndicator request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Quartz.Server.QYService.queryGisIndicatorResponse queryGisIndicator(Quartz.Server.QYService.queryGisIndicator request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Quartz.Server.QYService.queryIndicatorVOResponse queryIndicatorVO(Quartz.Server.QYService.queryIndicatorVO request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Quartz.Server.QYService.queryCategoryResponse queryCategory(Quartz.Server.QYService.queryCategory request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Quartz.Server.QYService.queryByCategoryResponse queryByCategory(Quartz.Server.QYService.queryByCategory request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Quartz.Server.QYService.transferQueryUnitResponse transferQueryUnit(Quartz.Server.QYService.transferQueryUnit request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Quartz.Server.QYService.transferDataTestResponse transferDataTest(Quartz.Server.QYService.transferDataTest request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Quartz.Server.QYService.queryUnitsResponse queryUnits(Quartz.Server.QYService.queryUnits request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Quartz.Server.QYService.queryBiIndicatorResponse queryBiIndicator(Quartz.Server.QYService.queryBiIndicator request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Quartz.Server.QYService.queryReportDataResponse queryReportData(Quartz.Server.QYService.queryReportData request);
        
        // CODEGEN: 参数“return”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Quartz.Server.QYService.queryReportTypeResponse queryReportType(Quartz.Server.QYService.queryReportType request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/")]
    public partial class reportIndicatorQueryVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string areaIdField;
        
        private string endDateField;
        
        private int endMonthField;
        
        private bool endMonthFieldSpecified;
        
        private int endQuarterField;
        
        private bool endQuarterFieldSpecified;
        
        private int endYearField;
        
        private bool endYearFieldSpecified;
        
        private string indicatorIdsField;
        
        private string indicatorNamesField;
        
        private string[] indicatorsField;
        
        private string reportTypeNameField;
        
        private string startDateField;
        
        private int startMonthField;
        
        private bool startMonthFieldSpecified;
        
        private int startQuarterField;
        
        private bool startQuarterFieldSpecified;
        
        private int startYearField;
        
        private bool startYearFieldSpecified;
        
        private int timeTypeField;
        
        private string unitIdField;
        
        private string unitNameField;
        
        private string unitTypeField;
        
        private int yearTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string areaId {
            get {
                return this.areaIdField;
            }
            set {
                this.areaIdField = value;
                this.RaisePropertyChanged("areaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
                this.RaisePropertyChanged("endDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int endMonth {
            get {
                return this.endMonthField;
            }
            set {
                this.endMonthField = value;
                this.RaisePropertyChanged("endMonth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endMonthSpecified {
            get {
                return this.endMonthFieldSpecified;
            }
            set {
                this.endMonthFieldSpecified = value;
                this.RaisePropertyChanged("endMonthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int endQuarter {
            get {
                return this.endQuarterField;
            }
            set {
                this.endQuarterField = value;
                this.RaisePropertyChanged("endQuarter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endQuarterSpecified {
            get {
                return this.endQuarterFieldSpecified;
            }
            set {
                this.endQuarterFieldSpecified = value;
                this.RaisePropertyChanged("endQuarterSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int endYear {
            get {
                return this.endYearField;
            }
            set {
                this.endYearField = value;
                this.RaisePropertyChanged("endYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endYearSpecified {
            get {
                return this.endYearFieldSpecified;
            }
            set {
                this.endYearFieldSpecified = value;
                this.RaisePropertyChanged("endYearSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string indicatorIds {
            get {
                return this.indicatorIdsField;
            }
            set {
                this.indicatorIdsField = value;
                this.RaisePropertyChanged("indicatorIds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string indicatorNames {
            get {
                return this.indicatorNamesField;
            }
            set {
                this.indicatorNamesField = value;
                this.RaisePropertyChanged("indicatorNames");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("indicators", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public string[] indicators {
            get {
                return this.indicatorsField;
            }
            set {
                this.indicatorsField = value;
                this.RaisePropertyChanged("indicators");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string reportTypeName {
            get {
                return this.reportTypeNameField;
            }
            set {
                this.reportTypeNameField = value;
                this.RaisePropertyChanged("reportTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
                this.RaisePropertyChanged("startDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int startMonth {
            get {
                return this.startMonthField;
            }
            set {
                this.startMonthField = value;
                this.RaisePropertyChanged("startMonth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startMonthSpecified {
            get {
                return this.startMonthFieldSpecified;
            }
            set {
                this.startMonthFieldSpecified = value;
                this.RaisePropertyChanged("startMonthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int startQuarter {
            get {
                return this.startQuarterField;
            }
            set {
                this.startQuarterField = value;
                this.RaisePropertyChanged("startQuarter");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startQuarterSpecified {
            get {
                return this.startQuarterFieldSpecified;
            }
            set {
                this.startQuarterFieldSpecified = value;
                this.RaisePropertyChanged("startQuarterSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public int startYear {
            get {
                return this.startYearField;
            }
            set {
                this.startYearField = value;
                this.RaisePropertyChanged("startYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startYearSpecified {
            get {
                return this.startYearFieldSpecified;
            }
            set {
                this.startYearFieldSpecified = value;
                this.RaisePropertyChanged("startYearSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public int timeType {
            get {
                return this.timeTypeField;
            }
            set {
                this.timeTypeField = value;
                this.RaisePropertyChanged("timeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string unitId {
            get {
                return this.unitIdField;
            }
            set {
                this.unitIdField = value;
                this.RaisePropertyChanged("unitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string unitName {
            get {
                return this.unitNameField;
            }
            set {
                this.unitNameField = value;
                this.RaisePropertyChanged("unitName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string unitType {
            get {
                return this.unitTypeField;
            }
            set {
                this.unitTypeField = value;
                this.RaisePropertyChanged("unitType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public int yearTime {
            get {
                return this.yearTimeField;
            }
            set {
                this.yearTimeField = value;
                this.RaisePropertyChanged("yearTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/")]
    public partial class biIndicatorNz : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int indicatorIdField;
        
        private bool indicatorIdFieldSpecified;
        
        private string indicatorNameField;
        
        private bool indicatorShowField;
        
        private bool indicatorShowFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int indicatorId {
            get {
                return this.indicatorIdField;
            }
            set {
                this.indicatorIdField = value;
                this.RaisePropertyChanged("indicatorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indicatorIdSpecified {
            get {
                return this.indicatorIdFieldSpecified;
            }
            set {
                this.indicatorIdFieldSpecified = value;
                this.RaisePropertyChanged("indicatorIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string indicatorName {
            get {
                return this.indicatorNameField;
            }
            set {
                this.indicatorNameField = value;
                this.RaisePropertyChanged("indicatorName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool indicatorShow {
            get {
                return this.indicatorShowField;
            }
            set {
                this.indicatorShowField = value;
                this.RaisePropertyChanged("indicatorShow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indicatorShowSpecified {
            get {
                return this.indicatorShowFieldSpecified;
            }
            set {
                this.indicatorShowFieldSpecified = value;
                this.RaisePropertyChanged("indicatorShowSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/")]
    public partial class indicatorCategoryNz : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime createTimeField;
        
        private bool createTimeFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private System.DateTime lastUpdateField;
        
        private bool lastUpdateFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime createTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
                this.RaisePropertyChanged("createTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createTimeSpecified {
            get {
                return this.createTimeFieldSpecified;
            }
            set {
                this.createTimeFieldSpecified = value;
                this.RaisePropertyChanged("createTimeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime lastUpdate {
            get {
                return this.lastUpdateField;
            }
            set {
                this.lastUpdateField = value;
                this.RaisePropertyChanged("lastUpdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastUpdateSpecified {
            get {
                return this.lastUpdateFieldSpecified;
            }
            set {
                this.lastUpdateFieldSpecified = value;
                this.RaisePropertyChanged("lastUpdateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/")]
    public partial class indicatorInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private int frequencyField;
        
        private bool frequencyFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private int indicatorTypeField;
        
        private bool indicatorTypeFieldSpecified;
        
        private string industryCodeField;
        
        private string nameField;
        
        private string statSystemNameField;
        
        private string unitField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int frequency {
            get {
                return this.frequencyField;
            }
            set {
                this.frequencyField = value;
                this.RaisePropertyChanged("frequency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool frequencySpecified {
            get {
                return this.frequencyFieldSpecified;
            }
            set {
                this.frequencyFieldSpecified = value;
                this.RaisePropertyChanged("frequencySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int indicatorType {
            get {
                return this.indicatorTypeField;
            }
            set {
                this.indicatorTypeField = value;
                this.RaisePropertyChanged("indicatorType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool indicatorTypeSpecified {
            get {
                return this.indicatorTypeFieldSpecified;
            }
            set {
                this.indicatorTypeFieldSpecified = value;
                this.RaisePropertyChanged("indicatorTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string industryCode {
            get {
                return this.industryCodeField;
            }
            set {
                this.industryCodeField = value;
                this.RaisePropertyChanged("industryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string statSystemName {
            get {
                return this.statSystemNameField;
            }
            set {
                this.statSystemNameField = value;
                this.RaisePropertyChanged("statSystemName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
                this.RaisePropertyChanged("unit");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/")]
    public partial class gisShowDataVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string areaNameField;
        
        private string indicatorNameField;
        
        private string indicatorValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string areaName {
            get {
                return this.areaNameField;
            }
            set {
                this.areaNameField = value;
                this.RaisePropertyChanged("areaName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string indicatorName {
            get {
                return this.indicatorNameField;
            }
            set {
                this.indicatorNameField = value;
                this.RaisePropertyChanged("indicatorName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string indicatorValue {
            get {
                return this.indicatorValueField;
            }
            set {
                this.indicatorValueField = value;
                this.RaisePropertyChanged("indicatorValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/")]
    public partial class gisCoordinate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string latitudeField;
        
        private string longitudeField;
        
        private string noField;
        
        private string pointField;
        
        private string unitNameField;
        
        private string warrantsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string no {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
                this.RaisePropertyChanged("point");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string unitName {
            get {
                return this.unitNameField;
            }
            set {
                this.unitNameField = value;
                this.RaisePropertyChanged("unitName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string warrants {
            get {
                return this.warrantsField;
            }
            set {
                this.warrantsField = value;
                this.RaisePropertyChanged("warrants");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/")]
    public partial class areaPerformNz : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string areaCodeField;
        
        private string areaDescField;
        
        private string areaNameField;
        
        private int areaSortField;
        
        private bool areaSortFieldSpecified;
        
        private string areaZimuCodeField;
        
        private string idField;
        
        private int isCoastField;
        
        private bool isCoastFieldSpecified;
        
        private string parentIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string areaCode {
            get {
                return this.areaCodeField;
            }
            set {
                this.areaCodeField = value;
                this.RaisePropertyChanged("areaCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string areaDesc {
            get {
                return this.areaDescField;
            }
            set {
                this.areaDescField = value;
                this.RaisePropertyChanged("areaDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string areaName {
            get {
                return this.areaNameField;
            }
            set {
                this.areaNameField = value;
                this.RaisePropertyChanged("areaName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int areaSort {
            get {
                return this.areaSortField;
            }
            set {
                this.areaSortField = value;
                this.RaisePropertyChanged("areaSort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areaSortSpecified {
            get {
                return this.areaSortFieldSpecified;
            }
            set {
                this.areaSortFieldSpecified = value;
                this.RaisePropertyChanged("areaSortSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string areaZimuCode {
            get {
                return this.areaZimuCodeField;
            }
            set {
                this.areaZimuCodeField = value;
                this.RaisePropertyChanged("areaZimuCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int isCoast {
            get {
                return this.isCoastField;
            }
            set {
                this.isCoastField = value;
                this.RaisePropertyChanged("isCoast");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isCoastSpecified {
            get {
                return this.isCoastFieldSpecified;
            }
            set {
                this.isCoastFieldSpecified = value;
                this.RaisePropertyChanged("isCoastSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string parentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
                this.RaisePropertyChanged("parentId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/")]
    public partial class systemCodedic : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string codeNameField;
        
        private string editModeField;
        
        private string enabledField;
        
        private string remarkField;
        
        private string sectionField;
        
        private string sectionNameField;
        
        private int sortNoField;
        
        private bool sortNoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codeName {
            get {
                return this.codeNameField;
            }
            set {
                this.codeNameField = value;
                this.RaisePropertyChanged("codeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string editMode {
            get {
                return this.editModeField;
            }
            set {
                this.editModeField = value;
                this.RaisePropertyChanged("editMode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string enabled {
            get {
                return this.enabledField;
            }
            set {
                this.enabledField = value;
                this.RaisePropertyChanged("enabled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string section {
            get {
                return this.sectionField;
            }
            set {
                this.sectionField = value;
                this.RaisePropertyChanged("section");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string sectionName {
            get {
                return this.sectionNameField;
            }
            set {
                this.sectionNameField = value;
                this.RaisePropertyChanged("sectionName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int sortNo {
            get {
                return this.sortNoField;
            }
            set {
                this.sortNoField = value;
                this.RaisePropertyChanged("sortNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sortNoSpecified {
            get {
                return this.sortNoFieldSpecified;
            }
            set {
                this.sortNoFieldSpecified = value;
                this.RaisePropertyChanged("sortNoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/")]
    public partial class indicatorQueryVO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string areaIdField;
        
        private string indicatorNameField;
        
        private string indicatorUnitField;
        
        private string indicatorValueField;
        
        private string reportTimeField;
        
        private string unitNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string areaId {
            get {
                return this.areaIdField;
            }
            set {
                this.areaIdField = value;
                this.RaisePropertyChanged("areaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string indicatorName {
            get {
                return this.indicatorNameField;
            }
            set {
                this.indicatorNameField = value;
                this.RaisePropertyChanged("indicatorName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string indicatorUnit {
            get {
                return this.indicatorUnitField;
            }
            set {
                this.indicatorUnitField = value;
                this.RaisePropertyChanged("indicatorUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string indicatorValue {
            get {
                return this.indicatorValueField;
            }
            set {
                this.indicatorValueField = value;
                this.RaisePropertyChanged("indicatorValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string reportTime {
            get {
                return this.reportTimeField;
            }
            set {
                this.reportTimeField = value;
                this.RaisePropertyChanged("reportTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string unitName {
            get {
                return this.unitNameField;
            }
            set {
                this.unitNameField = value;
                this.RaisePropertyChanged("unitName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryReportIndicator", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryReportIndicator {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Quartz.Server.QYService.reportIndicatorQueryVO arg0;
        
        public queryReportIndicator() {
        }
        
        public queryReportIndicator(Quartz.Server.QYService.reportIndicatorQueryVO arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryReportIndicatorResponse", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryReportIndicatorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Quartz.Server.QYService.indicatorQueryVO[] @return;
        
        public queryReportIndicatorResponse() {
        }
        
        public queryReportIndicatorResponse(Quartz.Server.QYService.indicatorQueryVO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryType", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryType {
        
        public queryType() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryTypeResponse", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Quartz.Server.QYService.systemCodedic[] @return;
        
        public queryTypeResponse() {
        }
        
        public queryTypeResponse(Quartz.Server.QYService.systemCodedic[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryAreaVO", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryAreaVO {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public queryAreaVO() {
        }
        
        public queryAreaVO(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryAreaVOResponse", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryAreaVOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Quartz.Server.QYService.areaPerformNz[] @return;
        
        public queryAreaVOResponse() {
        }
        
        public queryAreaVOResponse(Quartz.Server.QYService.areaPerformNz[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transferData", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class transferData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public transferData() {
        }
        
        public transferData(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transferDataResponse", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class transferDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public transferDataResponse() {
        }
        
        public transferDataResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryUnitsArea", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryUnitsArea {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public queryUnitsArea() {
        }
        
        public queryUnitsArea(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryUnitsAreaResponse", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryUnitsAreaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Quartz.Server.QYService.gisCoordinate[] @return;
        
        public queryUnitsAreaResponse() {
        }
        
        public queryUnitsAreaResponse(Quartz.Server.QYService.gisCoordinate[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateBiIndicator", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class updateBiIndicator {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public updateBiIndicator() {
        }
        
        public updateBiIndicator(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateBiIndicatorResponse", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class updateBiIndicatorResponse {
        
        public updateBiIndicatorResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryGisIndicator", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryGisIndicator {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg4;
        
        public queryGisIndicator() {
        }
        
        public queryGisIndicator(string arg0, string arg1, string arg2, string arg3, string arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryGisIndicatorResponse", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryGisIndicatorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Quartz.Server.QYService.gisShowDataVO[] @return;
        
        public queryGisIndicatorResponse() {
        }
        
        public queryGisIndicatorResponse(Quartz.Server.QYService.gisShowDataVO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryIndicatorVO", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryIndicatorVO {
        
        public queryIndicatorVO() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryIndicatorVOResponse", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryIndicatorVOResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Quartz.Server.QYService.indicatorInfo[] @return;
        
        public queryIndicatorVOResponse() {
        }
        
        public queryIndicatorVOResponse(Quartz.Server.QYService.indicatorInfo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryCategory", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryCategory {
        
        public queryCategory() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryCategoryResponse", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Quartz.Server.QYService.indicatorCategoryNz[] @return;
        
        public queryCategoryResponse() {
        }
        
        public queryCategoryResponse(Quartz.Server.QYService.indicatorCategoryNz[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryByCategory", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryByCategory {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public queryByCategory() {
        }
        
        public queryByCategory(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryByCategoryResponse", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryByCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Quartz.Server.QYService.biIndicatorNz[] @return;
        
        public queryByCategoryResponse() {
        }
        
        public queryByCategoryResponse(Quartz.Server.QYService.biIndicatorNz[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transferQueryUnit", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class transferQueryUnit {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public transferQueryUnit() {
        }
        
        public transferQueryUnit(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transferQueryUnitResponse", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class transferQueryUnitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public transferQueryUnitResponse() {
        }
        
        public transferQueryUnitResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transferDataTest", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class transferDataTest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public transferDataTest() {
        }
        
        public transferDataTest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="transferDataTestResponse", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class transferDataTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public transferDataTestResponse() {
        }
        
        public transferDataTestResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryUnits", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryUnits {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public queryUnits() {
        }
        
        public queryUnits(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryUnitsResponse", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryUnitsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public queryUnitsResponse() {
        }
        
        public queryUnitsResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryBiIndicator", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryBiIndicator {
        
        public queryBiIndicator() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryBiIndicatorResponse", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryBiIndicatorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Quartz.Server.QYService.biIndicatorNz[] @return;
        
        public queryBiIndicatorResponse() {
        }
        
        public queryBiIndicatorResponse(Quartz.Server.QYService.biIndicatorNz[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryReportData", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryReportData {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public queryReportData() {
        }
        
        public queryReportData(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryReportDataResponse", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryReportDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public queryReportDataResponse() {
        }
        
        public queryReportDataResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryReportType", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryReportType {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public queryReportType() {
        }
        
        public queryReportType(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryReportTypeResponse", WrapperNamespace="http://intf.ws.os.generaldata.com.cn/", IsWrapped=true)]
    public partial class queryReportTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://intf.ws.os.generaldata.com.cn/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public queryReportTypeResponse() {
        }
        
        public queryReportTypeResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IndicatorGisWSInterfaceChannel : Quartz.Server.QYService.IndicatorGisWSInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IndicatorGisWSInterfaceClient : System.ServiceModel.ClientBase<Quartz.Server.QYService.IndicatorGisWSInterface>, Quartz.Server.QYService.IndicatorGisWSInterface {
        
        public IndicatorGisWSInterfaceClient() {
        }
        
        public IndicatorGisWSInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IndicatorGisWSInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndicatorGisWSInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IndicatorGisWSInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quartz.Server.QYService.queryReportIndicatorResponse Quartz.Server.QYService.IndicatorGisWSInterface.queryReportIndicator(Quartz.Server.QYService.queryReportIndicator request) {
            return base.Channel.queryReportIndicator(request);
        }
        
        public Quartz.Server.QYService.indicatorQueryVO[] queryReportIndicator(Quartz.Server.QYService.reportIndicatorQueryVO arg0) {
            Quartz.Server.QYService.queryReportIndicator inValue = new Quartz.Server.QYService.queryReportIndicator();
            inValue.arg0 = arg0;
            Quartz.Server.QYService.queryReportIndicatorResponse retVal = ((Quartz.Server.QYService.IndicatorGisWSInterface)(this)).queryReportIndicator(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quartz.Server.QYService.queryTypeResponse Quartz.Server.QYService.IndicatorGisWSInterface.queryType(Quartz.Server.QYService.queryType request) {
            return base.Channel.queryType(request);
        }
        
        public Quartz.Server.QYService.systemCodedic[] queryType() {
            Quartz.Server.QYService.queryType inValue = new Quartz.Server.QYService.queryType();
            Quartz.Server.QYService.queryTypeResponse retVal = ((Quartz.Server.QYService.IndicatorGisWSInterface)(this)).queryType(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quartz.Server.QYService.queryAreaVOResponse Quartz.Server.QYService.IndicatorGisWSInterface.queryAreaVO(Quartz.Server.QYService.queryAreaVO request) {
            return base.Channel.queryAreaVO(request);
        }
        
        public Quartz.Server.QYService.areaPerformNz[] queryAreaVO(string arg0) {
            Quartz.Server.QYService.queryAreaVO inValue = new Quartz.Server.QYService.queryAreaVO();
            inValue.arg0 = arg0;
            Quartz.Server.QYService.queryAreaVOResponse retVal = ((Quartz.Server.QYService.IndicatorGisWSInterface)(this)).queryAreaVO(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quartz.Server.QYService.transferDataResponse Quartz.Server.QYService.IndicatorGisWSInterface.transferData(Quartz.Server.QYService.transferData request) {
            return base.Channel.transferData(request);
        }
        
        public string transferData(string arg0) {
            Quartz.Server.QYService.transferData inValue = new Quartz.Server.QYService.transferData();
            inValue.arg0 = arg0;
            Quartz.Server.QYService.transferDataResponse retVal = ((Quartz.Server.QYService.IndicatorGisWSInterface)(this)).transferData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quartz.Server.QYService.queryUnitsAreaResponse Quartz.Server.QYService.IndicatorGisWSInterface.queryUnitsArea(Quartz.Server.QYService.queryUnitsArea request) {
            return base.Channel.queryUnitsArea(request);
        }
        
        public Quartz.Server.QYService.gisCoordinate[] queryUnitsArea(string arg0, string arg1) {
            Quartz.Server.QYService.queryUnitsArea inValue = new Quartz.Server.QYService.queryUnitsArea();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Quartz.Server.QYService.queryUnitsAreaResponse retVal = ((Quartz.Server.QYService.IndicatorGisWSInterface)(this)).queryUnitsArea(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quartz.Server.QYService.updateBiIndicatorResponse Quartz.Server.QYService.IndicatorGisWSInterface.updateBiIndicator(Quartz.Server.QYService.updateBiIndicator request) {
            return base.Channel.updateBiIndicator(request);
        }
        
        public void updateBiIndicator(string arg0) {
            Quartz.Server.QYService.updateBiIndicator inValue = new Quartz.Server.QYService.updateBiIndicator();
            inValue.arg0 = arg0;
            Quartz.Server.QYService.updateBiIndicatorResponse retVal = ((Quartz.Server.QYService.IndicatorGisWSInterface)(this)).updateBiIndicator(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quartz.Server.QYService.queryGisIndicatorResponse Quartz.Server.QYService.IndicatorGisWSInterface.queryGisIndicator(Quartz.Server.QYService.queryGisIndicator request) {
            return base.Channel.queryGisIndicator(request);
        }
        
        public Quartz.Server.QYService.gisShowDataVO[] queryGisIndicator(string arg0, string arg1, string arg2, string arg3, string arg4) {
            Quartz.Server.QYService.queryGisIndicator inValue = new Quartz.Server.QYService.queryGisIndicator();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            Quartz.Server.QYService.queryGisIndicatorResponse retVal = ((Quartz.Server.QYService.IndicatorGisWSInterface)(this)).queryGisIndicator(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quartz.Server.QYService.queryIndicatorVOResponse Quartz.Server.QYService.IndicatorGisWSInterface.queryIndicatorVO(Quartz.Server.QYService.queryIndicatorVO request) {
            return base.Channel.queryIndicatorVO(request);
        }
        
        public Quartz.Server.QYService.indicatorInfo[] queryIndicatorVO() {
            Quartz.Server.QYService.queryIndicatorVO inValue = new Quartz.Server.QYService.queryIndicatorVO();
            Quartz.Server.QYService.queryIndicatorVOResponse retVal = ((Quartz.Server.QYService.IndicatorGisWSInterface)(this)).queryIndicatorVO(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quartz.Server.QYService.queryCategoryResponse Quartz.Server.QYService.IndicatorGisWSInterface.queryCategory(Quartz.Server.QYService.queryCategory request) {
            return base.Channel.queryCategory(request);
        }
        
        public Quartz.Server.QYService.indicatorCategoryNz[] queryCategory() {
            Quartz.Server.QYService.queryCategory inValue = new Quartz.Server.QYService.queryCategory();
            Quartz.Server.QYService.queryCategoryResponse retVal = ((Quartz.Server.QYService.IndicatorGisWSInterface)(this)).queryCategory(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quartz.Server.QYService.queryByCategoryResponse Quartz.Server.QYService.IndicatorGisWSInterface.queryByCategory(Quartz.Server.QYService.queryByCategory request) {
            return base.Channel.queryByCategory(request);
        }
        
        public Quartz.Server.QYService.biIndicatorNz[] queryByCategory(string arg0) {
            Quartz.Server.QYService.queryByCategory inValue = new Quartz.Server.QYService.queryByCategory();
            inValue.arg0 = arg0;
            Quartz.Server.QYService.queryByCategoryResponse retVal = ((Quartz.Server.QYService.IndicatorGisWSInterface)(this)).queryByCategory(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quartz.Server.QYService.transferQueryUnitResponse Quartz.Server.QYService.IndicatorGisWSInterface.transferQueryUnit(Quartz.Server.QYService.transferQueryUnit request) {
            return base.Channel.transferQueryUnit(request);
        }
        
        public string transferQueryUnit(string arg0) {
            Quartz.Server.QYService.transferQueryUnit inValue = new Quartz.Server.QYService.transferQueryUnit();
            inValue.arg0 = arg0;
            Quartz.Server.QYService.transferQueryUnitResponse retVal = ((Quartz.Server.QYService.IndicatorGisWSInterface)(this)).transferQueryUnit(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quartz.Server.QYService.transferDataTestResponse Quartz.Server.QYService.IndicatorGisWSInterface.transferDataTest(Quartz.Server.QYService.transferDataTest request) {
            return base.Channel.transferDataTest(request);
        }
        
        public string transferDataTest(string arg0) {
            Quartz.Server.QYService.transferDataTest inValue = new Quartz.Server.QYService.transferDataTest();
            inValue.arg0 = arg0;
            Quartz.Server.QYService.transferDataTestResponse retVal = ((Quartz.Server.QYService.IndicatorGisWSInterface)(this)).transferDataTest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quartz.Server.QYService.queryUnitsResponse Quartz.Server.QYService.IndicatorGisWSInterface.queryUnits(Quartz.Server.QYService.queryUnits request) {
            return base.Channel.queryUnits(request);
        }
        
        public string queryUnits(string arg0, string arg1) {
            Quartz.Server.QYService.queryUnits inValue = new Quartz.Server.QYService.queryUnits();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Quartz.Server.QYService.queryUnitsResponse retVal = ((Quartz.Server.QYService.IndicatorGisWSInterface)(this)).queryUnits(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quartz.Server.QYService.queryBiIndicatorResponse Quartz.Server.QYService.IndicatorGisWSInterface.queryBiIndicator(Quartz.Server.QYService.queryBiIndicator request) {
            return base.Channel.queryBiIndicator(request);
        }
        
        public Quartz.Server.QYService.biIndicatorNz[] queryBiIndicator() {
            Quartz.Server.QYService.queryBiIndicator inValue = new Quartz.Server.QYService.queryBiIndicator();
            Quartz.Server.QYService.queryBiIndicatorResponse retVal = ((Quartz.Server.QYService.IndicatorGisWSInterface)(this)).queryBiIndicator(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quartz.Server.QYService.queryReportDataResponse Quartz.Server.QYService.IndicatorGisWSInterface.queryReportData(Quartz.Server.QYService.queryReportData request) {
            return base.Channel.queryReportData(request);
        }
        
        public string queryReportData(string arg0, string arg1, string arg2) {
            Quartz.Server.QYService.queryReportData inValue = new Quartz.Server.QYService.queryReportData();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Quartz.Server.QYService.queryReportDataResponse retVal = ((Quartz.Server.QYService.IndicatorGisWSInterface)(this)).queryReportData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Quartz.Server.QYService.queryReportTypeResponse Quartz.Server.QYService.IndicatorGisWSInterface.queryReportType(Quartz.Server.QYService.queryReportType request) {
            return base.Channel.queryReportType(request);
        }
        
        public string[] queryReportType(string arg0) {
            Quartz.Server.QYService.queryReportType inValue = new Quartz.Server.QYService.queryReportType();
            inValue.arg0 = arg0;
            Quartz.Server.QYService.queryReportTypeResponse retVal = ((Quartz.Server.QYService.IndicatorGisWSInterface)(this)).queryReportType(inValue);
            return retVal.@return;
        }
    }
}
